# dnf packages
dnf_repositories:
  - repo: docker-ce
    url: https://download.docker.com/linux/fedora/docker-ce.repo
  - repo: vivaldi
    url: https://repo.vivaldi.com/archive/vivaldi-fedora.repo
  - repo: vscode
    path: "{{ playbook_dir }}/repos/vscode.repo"
  # - repo: virtualbox # Does not have release 37 # virtualbox
  #   url: https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo

dnf_packages: [ # virtualbox
  make, gcc, g++, curl, unzip, tar, zsh, rcm, the_silver_searcher, vim, htop, iftop, git, tig, ranger, gnome-tweaks,
  gnome-extensions-app, python3-pip, python3-psutil, nodejs, docker-ce, docker-ce-cli, containerd.io,
  docker-compose-plugin, vagrant, code, golang, kitty, fzf, vivaldi-stable
]

clean_packages: [
  gnome-terminal, gnome-calculator, gnome-boxes, gnome-calendar, gnome-characters, gnome-clocks, gnome-contacts,
  gnome-photos, gnome-maps, gnome-tour, gnome-weather, gnome-logs, gnome-software, cheese, yelp, libreoffice-*, totem,
  simple-scan, rhythmbox, firefox
]

# flatpack packages
flatpak_remotes:
  - repo: flathub
    url: https://flathub.org/repo/flathub.flatpakrepo

flatpak_packages:
  - com.spotify.Client
  - org.telegram.desktop
  - com.bitwarden.desktop
  - org.videolan.VLC

# system configuration
sys_xterm: /usr/bin/kitty

# user configuration
user_shell: /usr/bin/zsh

user_shell_plugins:
  - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    version: 0.7.1
    dest: .config/zsh/plugins/zsh-syntax-highlighting

user_groups: [docker]

user_folders:
  - .config/me
  - .config/zsh/plugins
  - .local/bin
  - .local/go
  - .local/npm
  - .themes
  - .fonts
  - dev

user_dotfiles: 
  repo: https://github.com/dobleme/dotfiles.git
  dest: dev/dotfiles
  ref: main
