---
- hosts: all

  name: Main playbook to run all the tasks

  pre_tasks:
    - name: Check required packages to run this playbook
      ansible.builtin.package:
        name:
          - python3-apt
          - python3-psutil
        state: present
      check_mode: true
      tags: always

    - name: Check user is defined
      when: user is undefined
      ansible.builtin.set_fact:
        user: "{{ ansible_facts.user_id }}"
      tags: always

    - name: Check home dir is defined
      when: home is undefined
      ansible.builtin.set_fact:
        home: "/home/{{ user }}"
      tags: always

  tasks:
    - name: Install essential packages
      ansible.builtin.import_tasks: tasks/essentials.yml
      become: true
      tags:
        - never
        - essentials

    - name: Configure ssh client
      ansible.builtin.import_tasks: tasks/ssh.yml
      tags: ssh

    - name: Configure user
      ansible.builtin.import_tasks: tasks/user.yml
      tags: user

    - name: Install extra packages
      ansible.builtin.import_tasks: tasks/extra-packages.yml
      tags: extra

    - name: Install and configure zsh shell
      ansible.builtin.import_tasks: tasks/shell.yml
      tags: shell

    - name: Install and configure kitty xterm
      ansible.builtin.import_tasks: tasks/xterm.yml
      tags: xterm

    - name: Configure GNOME user
      ansible.builtin.import_tasks: tasks/gnome.yml
      tags: gnome
