---
- hosts: all

  name: Main playbook to run all the tasks

  vars_files:
    - config.yml
    - gnome.yml

  pre_tasks:
    - name: Check user is defined
      when: user is undefined
      ansible.builtin.set_fact:
        user: "{{ ansible_facts.user_id }}"
      tags: ["always"]

    - name: Check home dir is defined
      when: home is undefined
      ansible.builtin.set_fact:
        home: "/home/{{ user }}"
      tags: ["always"]

  tasks:
    - name: Clean unneded packages
      ansible.builtin.import_tasks: tasks/clean.yml
      become: true
      tags: ["never", "clean"]

    - name: Install essential packages
      ansible.builtin.import_tasks: tasks/essentials.yml
      become: true
      tags: ["essentials"]

    - name: Configure system
      ansible.builtin.import_tasks: tasks/system.yml
      become: true
      tags: ["system"]

    - name: Configure user
      ansible.builtin.import_tasks: tasks/user.yml
      tags: ["user"]

    - name: Configure GNOME user
      ansible.builtin.import_tasks: tasks/gnome.yml
      tags: ["user", "gnome"]
