---
- name: Ubuntu essentials
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '22'
  ansible.builtin.include_tasks: "ubuntu-essentials.yml"

- name: Fedora essentials
  when: ansible_distribution == 'Fedora' and ansible_distribution_major_version == '37'
  ansible.builtin.include_tasks: "fedora-essentials.yml"
