---
- name: Install Pip packages.
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    state: latest
    extra_args: --user

- name: Install NPM packages.
  community.general.npm:
    name: "{{ item }}"
    state: latest
    global: true
  loop: "{{ npm_packages }}"

- name: Install Go packages
  ansible.builtin.command: go install "{{ item }}"
  loop: "{{ go_packages }}"
