---
- name: Create base user folders
  ansible.builtin.file:
    path: "{{ home }}/{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ user_folders }}"

- name: Clone/Pull dotfiles
  when: user_dotfiles is defined
  ansible.builtin.git:
    repo: "{{ user_dotfiles.repo }}"
    dest: "{{ home }}/{{ user_dotfiles.dest }}"
    version: "{{ user_dotfiles.ref }}"
    clone: true
    update: true

- name: Create/Update dotfiles symlinks
  when: user_dotfiles is defined
  block:
    - name: Copy .rcrc
      ansible.builtin.copy:
        src: "{{ home }}/{{ user_dotfiles.dest }}/.rcrc"
        dest: "{{ home }}/.rcrc"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0664
      register: res
    - name: Link the dotfiles
      when: res.changed
      ansible.builtin.command:
        cmd: rcup -f -d "{{ home }}/{{ user_dotfiles.dest }}"
        chdir: "{{ home }}"

- name: Create hide desktop entry
  ansible.builtin.copy:
    dest: "{{ home }}/.local/share/applications/hide"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0664
    content: |
      [Desktop Entry]
      NoDisplay=true

- name: Hide desktop entries
  when: (user_desktop_entiries is defined) and (user_desktop_entiries | length > 0)
  ansible.builtin.file:
    src: "{{ home }}/.local/share/applications/hide"
    dest: "{{ home }}/.local/share/applications/{{ item }}.desktop"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  loop: "{{ user_desktop_entiries }}"

- name: Add groups to {{ user }}
  when: user_groups is defined
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: "{{ user_groups }}"
    append: true
