---
- name: Check code package is installed
  ansible.builtin.package:
    name: code
    state: present
  check_mode: true

- name: Install vscode fonts
  ansible.builtin.include_tasks: "lib/install-fonts.yml"
  vars:
    owner: "{{ user }}"
    fonts: "{{ vscode_fonts }}"

- name: Check installed vscode extensions
  ansible.builtin.shell:
    cmd: code --list-extensions | grep "{{ item | lower }}"
  register: result
  failed_when: false
  changed_when: false
  loop: "{{ vscode_extensions }}"

- name: Installing vscode extensions
  when: item.rc != 0
  ansible.builtin.command: code --install-extension "{{ item.item }}"
  loop: "{{ result.results }}"
