# Essential configuration
builtin_packages: [
  make, gcc, g++, curl, unzip, tar, zsh, rcm, vim, htop, iftop, git, tig, ranger, gnome-tweaks,
  gnome-extensions-app, python3-pip, kitty, fzf
]

builtin_repositories: []

alt_packages: []

# SSH client configuration
ssh_folders: []

ssh_keys: []

# Shell configuration
shell_bin: /usr/bin/zsh

shell_folders:
  - .config/zsh/plugins
  - .local/bin

shell_plugins:
  - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    version: 0.7.1
    dest: .config/zsh/plugins/zsh-syntax-highlighting
  - repo: https://github.com/junegunn/fzf.git
    version: 0.37.0
    dest: .config/zsh/plugins/fzf

# Xterm configuration
xterm_bin: /usr/bin/kitty

xterm_folders:
  - .fonts

xterm_fonts:
  - url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.0/CascadiaCode.zip
    dir: CascadiaCode
    fonts:
      - 'Caskaydia Cove Nerd Font Complete Mono Bold Italic.otf'
      - 'Caskaydia Cove Nerd Font Complete Mono Bold.otf'
      - 'Caskaydia Cove Nerd Font Complete Mono ExtraLight Italic.otf'
      - 'Caskaydia Cove Nerd Font Complete Mono ExtraLight.otf'
      - 'Caskaydia Cove Nerd Font Complete Mono Italic.otf'
      - 'Caskaydia Cove Nerd Font Complete Mono Light Italic.otf'
      - 'Caskaydia Cove Nerd Font Complete Mono Light.otf'
      - 'Caskaydia Cove Nerd Font Complete Mono Regular.otf'
      - 'Caskaydia Cove Nerd Font Complete Mono SemiBold Italic.otf'
      - 'Caskaydia Cove Nerd Font Complete Mono SemiBold.otf'
      - 'Caskaydia Cove Nerd Font Complete Mono SemiLight Italic.otf'
      - 'Caskaydia Cove Nerd Font Complete Mono SemiLight.otf'

# User configuration
user_folders:
  - .config/me
  - .themes
  - dev

user_groups: []

user_dotfiles:
  repo: https://github.com/dobleme/dotfiles.git
  dest: dev/dotfiles
  ref: main

user_desktop_entiries: []

# Extra packages
pip_packages:
  - pytest
  - ansible-lint

npm_packages: []

go_packages:
  - golang.org/x/tools/gopls@latest

# VSCode
vscode_extensions: []

vscode_fonts:
  - url: https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip
    dir: JetBrainsMono
    fonts:
      - 'fonts/ttf/JetBrainsMono-BoldItalic.ttf'
      - 'fonts/ttf/JetBrainsMono-Bold.ttf'
      - 'fonts/ttf/JetBrainsMono-ExtraBoldItalic.ttf'
      - 'fonts/ttf/JetBrainsMono-ExtraBold.ttf'
      - 'fonts/ttf/JetBrainsMono-ExtraLightItalic.ttf'
      - 'fonts/ttf/JetBrainsMono-ExtraLight.ttf'
      - 'fonts/ttf/JetBrainsMono-Italic.ttf'
      - 'fonts/ttf/JetBrainsMono-LightItalic.ttf'
      - 'fonts/ttf/JetBrainsMono-Light.ttf'
      - 'fonts/ttf/JetBrainsMono-MediumItalic.ttf'
      - 'fonts/ttf/JetBrainsMono-Medium.ttf'
      - 'fonts/ttf/JetBrainsMono-Regular.ttf'
      - 'fonts/ttf/JetBrainsMono-SemiBoldItalic.ttf'
      - 'fonts/ttf/JetBrainsMono-SemiBold.ttf'
      - 'fonts/ttf/JetBrainsMono-ThinItalic.ttf'
      - 'fonts/ttf/JetBrainsMono-Thin.ttf'
