# Essential configuration
builtin_packages: [
  make, gcc, g++, curl, unzip, tar, zsh, rcm, silversearcher-ag, vim, btop, iftop, git, tig, ranger, nala, bat,
  gnome-tweaks, gnome-extensions-app, python3-pip, kitty, vivaldi-stable, php8.1, golang-go, code, google-cloud-cli,
  kubectl, google-cloud-sdk-gke-gcloud-auth-plugin, nodejs
]

builtin_repositories:
  - 'ppa:ondrej/php'
  - name: vivaldi
    url: https://repo.vivaldi.com/archive/linux_signing_key.pub
    list: "deb [arch=amd64] https://repo.vivaldi.com/archive/deb/ stable main"
  - name: vscode
    url: https://packages.microsoft.com/keys/microsoft.asc
    list: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
  - name: gcloud
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    list: "deb [signed-by=/usr/share/keyrings/gcloud.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    key_dest: /usr/share/keyrings/gcloud.gpg
  - name: k8s
    list: "deb [signed-by=/usr/share/keyrings/gcloud.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
  - name: nodejs
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    list: "deb https://deb.nodesource.com/node_18.x jammy main\ndeb-src https://deb.nodesource.com/node_18.x jammy main"

alt_packages:
  - spotify
  - telegram-desktop
  - bitwarden
  - vlc
  - slack
  - marktext

# SSH client configuration
ssh_folders:
  - .ssh/work
  - .ssh/personal

ssh_keys:
  - .ssh/work/git
  - .ssh/personal/git
  - .ssh/personal/lab

# User configuration
user_folders:
  - .config/me
  - .local/go
  - .local/npm
  - .themes
  - dev/work

user_groups:
  - docker

user_desktop_entiries:
  - htop
  - ranger
  - vim
  - gnome-language-selector
  - org.gnome.PowerStats
  - info

# Extra packages
npm_packages:
  - '@slidev/cli'
  - '@slidev/theme-default'

# VSCode
vscode_extensions:
  - rocketseat.theme-omni
  - ms-python.python
  - golang.Go
  - tamasfe.even-better-toml
  - redhat.vscode-yaml
